[project]
name = "eit-scan"
version = "0.1.0"
description = "Tool for performing EIT scans"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pyside6>=6.10.0",
    "pyvisa>=1.15.0",
    "pyvisa-py>=0.8.1",
]
